---
- name: Ansible playbook for login to openshift
  hosts: localhost
  connection: local
  vars:
    openshift_username: system
    openshift_password: admin
  tasks:
     - name: Create Project
       command: oc login https://10.20.14.183:8443/ -u system -p admin
     - name: Changing webapp project
       command: oc project xortest
     - name: New app creating
       command: oc new-app --name=mywebapp https://github.com/satishthakare/xortest.git --strategy=docker
     - name: Exposing Service
       command: oc expose service/mywebapp
...
